language: java
jdk:
  - openjdk8

script: mvn test -B -P travis

deploy:
  provider: script
  script: mvn deploy --settings .travis/settings.xml -P travis
  on:
    branch: master
    # tags are currently build manually, which already include the deployment
    tags: false
